export default {
  FIAT_FETCH_PAYMENTSYSTEM_LIST: 'FIAT_FETCH_PAYMENTSYSTEM_LIST',
  FIAT_FETCH_PAYMENTSYSTEM_LIST_ERROR: 'FIAT_FETCH_PAYMENTSYSTEM_LIST_ERROR',
  FIAT_FETCH_PAYMENTSYSTEM_LIST_SUCCESS: 'FIAT_FETCH_PAYMENTSYSTEM_LIST_SUCCESS',

  FIAT_FETCH_REQUEST_FIAT: 'FIAT_FETCH_REQUEST_FIAT_URL',
  FIAT_FETCH_REQUEST_FIAT_ERROR: 'FIAT_FETCH_REQUEST_FIAT_URL_ERROR',
  FIAT_FETCH_REQUEST_FIAT_SUCCESS: 'FIAT_FETCH_REQUEST_FIAT_URL_SUCCESS',

  FIAT_UPDATE_FORM: 'FIAT_UPDATE_FORM',
  FIAT_ERROR_FORM: 'FIAT_ERROR_FORM',
  FIAT_LEAVE_PAGE: 'FIAT_LEAVE_PAGE'
}
