export default {
  COUPON_CREATE_COUPON: 'COUPON_CREATE_COUPON',
  COUPON_CREATE_COUPON_ERROR: 'COUPON_CREATE_COUPON_ERROR',
  COUPON_CREATE_COUPON_SUCCESS: 'COUPON_CREATE_COUPON_SUCCESS',
  
  COUPON_CREATE_UPDATE_FORM: 'COUPON_CREATE_UPDATE_FORM',
  COUPON_CREATE_VALIDATE_FORM: 'COUPON_CREATE_VALIDATE_FORM'
};