export default Object.assign({
  REFERRAL_FETCH_USER_LIST: 'REFERRAL_FETCH_USER_LIST',
  REFERRAL_FETCH_USER_LIST_ERROR: 'REFERRAL_FETCH_USER_LIST_ERROR',
  REFERRAL_FETCH_USER_LIST_SUCCESS: 'REFERRAL_FETCH_USER_LIST_SUCCESS',
  REFERRAL_UPDATE_LIST: 'REFERRAL_UPDATE_LIST',
  REFERRAL_LEAVE_PAGE: 'REFERRAL_LEAVE_PAGE',
  REFERRAL_UPDATE_FILTER: 'REFERRAL_UPDATE_FILTER'
});