export default {
  ACTIVATIONS_TRANSACTION_FETCH_CODE: 'ACTIVATIONS_TRANSACTION_FETCH_CODE',
  ACTIVATIONS_TRANSACTION_FETCH_CODE_ERROR: 'ACTIVATIONS_TRANSACTION_FETCH_CODE_ERROR',
  ACTIVATIONS_TRANSACTION_FETCH_CODE_SUCCESS: 'ACTIVATIONS_TRANSACTION_FETCH_CODE_SUCCESS',
  ACTIVATIONS_TRANSACTION_LEAVE_PAGE: 'ACTIVATIONS_TRANSACTION_LEAVE_PAGE'
};