export default {
  MINING_CURRENT_LOAD_INFO: 'MINING_CURRENT_LOAD_INFO',
  MINING_CURRENT_LOAD_INFO_SUCCESS: 'MINING_CURRENT_LOAD_INFO_SUCCESS',
  MINING_CURRENT_LOAD_INFO_ERROR: 'MINING_CURRENT_LOAD_INFO_ERROR',

  MINING_CURRENT_LOAD_TRANSACTION: 'MINING_CURRENT_LOAD_TRANSACTION',
  MINING_CURRENT_LOAD_TRANSACTION_ERROR: 'MINING_CURRENT_LOAD_TRANSACTION_ERROR',
  MINING_CURRENT_LOAD_TRANSACTION_SUCCESS: 'MINING_CURRENT_LOAD_TRANSACTION_SUCCESS',

  MINING_CURRENT_LOAD_CHART: 'MINING_CURRENT_LOAD_CHART',
  MINING_CURRENT_LOAD_CHART_ERROR: 'MINING_CURRENT_LOAD_CHART_ERROR',
  MINING_CURRENT_LOAD_CHART_SUCCESS: 'MINING_CURRENT_LOAD_CHART_SUCCESS'
}