export default {
  USERS_REGISTRATION_UPDATE_FORM: 'USERS_REGISTRATION_UPDATE_FORM',
  USERS_REGISTRATION_FETCH_FORM: 'USERS_REGISTRATION_FETCH_FORM',
  USERS_REGISTRATION_FETCH_FORM_ERROR: 'USERS_REGISTRATION_FETCH_FORM_ERROR',
  USERS_REGISTRATION_FETCH_FORM_SUCCESS: 'USERS_REGISTRATION_FETCH_FORM_SUCCESS',
  USERS_REGISTRATION_FORM_ERROR: 'USERS_REGISTRATION_FORM_ERROR',
  USERS_REGISTRATION_LEAVE_PAGE: 'USERS_REGISTRATION_LEAVE_PAGE',
};