export default {
  MINING_DEPOSIT_SHOW_MODAL: 'MINING_DEPOSIT_SHOW_MODAL',
  MINING_DEPOSIT_CLOSE_MODAL: 'MINING_DEPOSIT_CLOSE_MODAL',

  MINING_DEPOSIT_UPDATE_FORM: 'MINING_DEPOSIT_UPDATE_FORM',
  MINING_DEPOSIT_VALIDATE_FORM: 'MINING_DEPOSIT_VALIDATE_FORM',

  MINING_DEPOSIT: 'MINING_DEPOSIT',
  MINING_DEPOSIT_ERROR: 'MINING_DEPOSIT_ERROR',
  MINING_DEPOSIT_SUCCESS: 'MINING_DEPOSIT_SUCCESS'
};