export default {
  EXCHANGE_UPDATE_FORM: 'EXCHANGE_UPDATE_FORM',
  EXCHANGE_UPDATE_INPUTS: 'EXCHANGE_UPDATE_INPUTS',
  EXCHANGE_UPDATE_SELECTS: 'EXCHANGE_UPDATE_SELECTS',

  EXCHANGE_FETCH_FORM: 'EXCHANGE_FETCH_FORM',
  EXCHANGE_FETCH_FORM_ERROR: 'EXCHANGE_FETCH_FORM_ERROR',
  EXCHANGE_FETCH_FORM_SUCCESS: 'EXCHANGE_FETCH_FORM_SUCCESS',


  EXCHANGE_FETCH_CHART_DATA: 'EXCHANGE_FETCH_CHART_DATA',
  EXCHANGE_FETCH_CHART_DATA_ERROR: 'EXCHANGE_FETCH_CHART_DATA_ERROR',
  EXCHANGE_FETCH_CHART_DATA_SUCCESS: 'EXCHANGE_FETCH_CHART_DATA_SUCCESS'
}
