export default {
  USERS_PROFILE_LOGOUT: 'USERS_PROFILE_LOGOUT',
  USERS_PROFILE_LOGOUT_SUCCESS: 'USERS_PROFILE_LOGOUT',
  USERS_PROFILE_LOGOUT_ERROR: 'USERS_PROFILE_LOGOUT_ERROR',

  USERS_PROFILE_FETCH_INFO: 'USERS_PROFILE_FETCH_INFO',
  USERS_PROFILE_FETCH_INFO_ERROR: 'USERS_PROFILE_FETCH_INFO_ERROR',
  USERS_PROFILE_FETCH_INFO_NETWORK_ERROR: 'USERS_PROFILE_FETCH_INFO_NETWORK_ERROR',
  USERS_PROFILE_FETCH_INFO_SUCCESS: 'USERS_PROFILE_FETCH_INFO_SUCCESS',

  USERS_PROFILE_FETCH_LIST_WALLET: 'USERS_PROFILE_FETCH_LIST_WALLET',
  USERS_PROFILE_FETCH_LIST_WALLET_ERROR: 'USERS_PROFILE_FETCH_LIST_WALLET_ERROR',
  USERS_PROFILE_FETCH_LIST_WALLET_SUCCESS: 'USERS_PROFILE_FETCH_LIST_WALLET_SUCCESS',
  USERS_PROFILE_FETCH_LIST_WALLET_NETWORK_ERROR: 'USERS_PROFILE_FETCH_LIST_WALLET_NETWORK_ERROR',

  USERS_PROFILE_FETCH_LIST_RATES: 'USERS_PROFILE_FETCH_LIST_RATES',
  USERS_PROFILE_FETCH_LIST_RATES_ERROR: 'USERS_PROFILE_FETCH_LIST_RATES_ERROR',
  USERS_PROFILE_FETCH_LIST_RATES_SUCCESS: 'USERS_PROFILE_FETCH_LIST_RATES_SUCCESS',

  FETCH_LIST_CURRENCY: 'FETCH_LIST_CURRENCY',
  FETCH_LIST_CURRENCY_ERROR: 'FETCH_LIST_CURRENCY_ERROR',
  FETCH_LIST_CURRENCY_SUCCESS: 'FETCH_LIST_CURRENCY_SUCCESS'
};
