export default {
  USERS_PROFILE_LOGOUT: 'USERS_PROFILE_LOGOUT',
  USERS_PROFILE_LOGOUT_SUCCESS: 'USERS_PROFILE_LOGOUT',
  USERS_PROFILE_LOGOUT_ERROR: 'USERS_PROFILE_LOGOUT_ERROR',

  USERS_PROFILE_FETCH_INFO: 'USERS_PROFILE_FETCH_INFO',
  USERS_PROFILE_FETCH_INFO_ERROR: 'USERS_PROFILE_FETCH_INFO_ERROR',
  USERS_PROFILE_FETCH_INFO_NETWORK_ERROR: 'USERS_PROFILE_FETCH_INFO_NETWORK_ERROR',
  USERS_PROFILE_FETCH_INFO_SUCCESS: 'USERS_PROFILE_FETCH_INFO_SUCCESS',
};