export default {
  USERS_SETTINGS_QRCODE_UPDATE_FORM: 'USERS_SETTINGS_QRCODE_UPDATE_FORM',
  USERS_SETTINGS_QRCODE_GET_URL: 'USERS_SETTINGS_QRCODE_GET_URL',
  USERS_SETTINGS_QRCODE_GET_URL_ERROR: 'USERS_SETTINGS_QRCODE_GET_URL_ERROR',
  USERS_SETTINGS_QRCODE_GET_URL_SUCCESS: 'USERS_SETTINGS_QRCODE_GET_URL_SUCCESS',
  USERS_SETTINGS_QRCODE_ERROR_FORM: 'USERS_SETTINGS_QRCODE_ERROR_FORM',

  USERS_SETTINGS_QRCODE_SET_ENABLE_2FA: 'USERS_SETTINGS_QRCODE_SET_ENABLE_2FA',
  USERS_SETTINGS_QRCODE_SET_ENABLE_2FA_ERROR: 'USERS_SETTINGS_QRCODE_SET_ENABLE_2FA_ERROR',
  USERS_SETTINGS_QRCODE_SET_ENABLE_2FA_SUCCESS: 'USERS_SETTINGS_QRCODE_SET_ENABLE_2FA_SUCCESS'
}