export default {
  USERS_LOGIN_UPDATE_FORM: 'USERS_LOGIN_UPDATE_FORM',
  USERS_AUTH_UPDATE_FORM: 'USERS_AUTH_UPDATE_FORM',
  USERS_AUTH_CANCEL: 'USERS_AUTH_CANCEL',
  USERS_LOGIN_FETCH_FORM: 'USERS_LOGIN_FETCH_FORM',
  USERS_LOGIN_FETCH_FORM_ERROR: 'USERS_LOGIN_FETCH_FORM_ERROR',
  USERS_LOGIN_FETCH_FORM_SUCCESS: 'USERS_LOGIN_FETCH_FORM_SUCCESS',
  USERS_LOGIN_FORM_ERROR: 'USERS_LOGIN_FORM_ERROR',
  USERS_AUTH_FORM_ERROR: 'USERS_AUTH_FORM_ERROR',
  USERS_AUTH_FETCH_FORM: 'USERS_AUTH_FETCH_FORM',
  USERS_AUTH_FETCH_FORM_ERROR: 'USERS_AUTH_FETCH_FORM_ERROR',
  USERS_AUTH_FETCH_FORM_SUCCESS: 'USERS_AUTH_FETCH_FORM_SUCCESS',
  USERS_LOGIN_LEAVE_PAGE: 'USERS_LOGIN_LEAVE_PAGE',
  USERS_LOGIN_CONTENT_AUTHENTICATION: 'USERS_LOGIN_CONTENT_AUTHENTICATION'
}