export default {
  MINING_WITHDRAW_SHOW_MODAL: 'MINING_WITHDRAW_SHOW_MODAL',
  MINING_WITHDRAW_CLOSE_MODAL: 'MINING_WITHDRAW_CLOSE_MODAL',

  MINING_WITHDRAW_UPDATE_FORM: 'MINING_WITHDRAW_UPDATE_FORM',
  MINING_WITHDRAW_VALIDATE_FORM: 'MINING_WITHDRAW_VALIDATE_FORM',

  MINING_WITHDRAW: 'MINING_WITHDRAW',
  MINING_WITHDRAW_ERROR: 'MINING_WITHDRAW_ERROR',
  MINING_WITHDRAW_SUCCESS: 'MINING_WITHDRAW_SUCCESS'
};