export default {
  REPLENISHMENT_TOKEN_FETCH: 'REPLENISHMENT_TOKEN_FETCH',
  REPLENISHMENT_TOKEN_FETCH_ERROR: 'REPLENISHMENT_TOKEN_FETCH_ERROR',
  REPLENISHMENT_TOKEN_FETCH_SUCCESS: 'REPLENISHMENT_TOKEN_FETCH_SUCCESS'
}