import fiat from './components/Fiat/constants';

export default {
  REPLENISHMENT_TOKEN_FETCH: 'REPLENISHMENT_TOKEN_FETCH',
  REPLENISHMENT_TOKEN_FETCH_ERROR: 'REPLENISHMENT_TOKEN_FETCH_ERROR',
  REPLENISHMENT_TOKEN_FETCH_SUCCESS: 'REPLENISHMENT_TOKEN_FETCH_SUCCESS',

  FETCH_AUTO_CONVERT: 'FETCH_AUTO_CONVERT',
  FETCH_AUTO_CONVERT_SUCCESS: 'FETCH_AUTO_CONVERT_SUCCESS',
  FETCH_AUTO_CONVERT_ERROR: 'FETCH_AUTO_CONVERT_ERROR',
  ...fiat
};
