export default {
  USERS_SETTINGS_PASSWORD_UPDATE_FORM: 'USERS_SETTINGS_PASSWORD_UPDATE_FORM',
  USERS_SETTINGS_PASSWORD_SUBMIT_FORM: 'USERS_SETTINGS_PASSWORD_SUBMIT_FORM',
  USERS_SETTINGS_PASSWORD_SUBMIT_FORM_ERROR: 'USERS_SETTINGS_PASSWORD_SUBMIT_FORM_ERROR',
  USERS_SETTINGS_PASSWORD_SUBMIT_FORM_SUCCESS: 'USERS_SETTINGS_PASSWORD_SUBMIT_FORM_SUCCESS',
  USERS_SETTINGS_PASSWORD_FORM_ERROR: 'USERS_SETTINGS_PASSWORD_FORM_ERROR',
}