export default {
  COUPON_ACTIVATE_UPDATE_FORM: 'COUPON_ACTIVATE_UPDATE_FORM',
  
  COUPON_ACTIVATE_SEND_FORM: 'COUPON_ACTIVATE_SEND_FORM',
  COUPON_ACTIVATE_SEND_FORM_ERROR: 'COUPON_ACTIVATE_SEND_FORM_ERROR',
  COUPON_ACTIVATE_SEND_FORM_SUCCESS: 'COUPON_ACTIVATE_SEND_FORM_SUCCESS'
};