export default {
  USERS_ACTIVATION_UPDATE_FORM: 'USERS_ACTIVATION_UPDATE_FORM',
  USERS_ACTIVATION_FETCH_FORM: 'USERS_ACTIVATION_FETCH_FORM',
  USERS_ACTIVATION_FETCH_FORM_ERROR: 'USERS_ACTIVATION_FETCH_FORM_ERROR',
  USERS_ACTIVATION_FETCH_FORM_SUCCESS: 'USERS_ACTIVATION_FETCH_FORM_SUCCESS',
  USERS_ACTIVATION_FORM_ERROR: 'USERS_ACTIVATION_FORM_ERROR',
  USERS_ACTIVATION_LEAVE_PAGE: 'USERS_ACTIVATION_LEAVE_PAGE',
}