export default Object.assign({
  WITHDRAW_UPDATE_FORM: 'WITHDRAW_UPDATE_FORM',
  WITHDRAW_FETCH_FORM: 'USERS_LOGIN_FETCH_FORM',
  WITHDRAW_FETCH_FORM_ERROR: 'USERS_LOGIN_FETCH_FORM_ERROR',
  WITHDRAW_FETCH_FORM_SUCCESS: 'USERS_LOGIN_FETCH_FORM_SUCCESS',
  WITHDRAW_FORM_ERROR: 'WITHDRAW_FORM_ERROR',
  WITHDRAW_LEAVE_PAGE: 'USERS_LOGIN_LEAVE_PAGE',
},);