export default Object.assign({
  WITHDRAW_UPDATE_FORM: 'WITHDRAW_UPDATE_FORM',
  WITHDRAW_FETCH_FORM: 'WITHDRAW_FETCH_FORM',
  WITHDRAW_FETCH_FORM_ERROR: 'WITHDRAW_FETCH_FORM_ERROR',
  WITHDRAW_FETCH_FORM_SUCCESS: 'WITHDRAW_FETCH_FORM_SUCCESS',
  WITHDRAW_FORM_ERROR: 'WITHDRAW_FORM_ERROR',
  WITHDRAW_LEAVE_PAGE: 'WITHDRAW_LEAVE_PAGE',
  INIT_WITHDRAW: 'INIT_WITHDRAW',
},);
