export default {
  MINING_CREATE: 'MINING_CREATE',
  MINING_CREATE_ERROR: 'MINING_CREATE_ERROR',
  MINING_CREATE_SUCCESS: 'MINING_CREATE_SUCCESS',

  MINING_CREATE_UPDATE_FORM: 'MINING_CREATE_UPDATE_FORM',
  MINING_CREATE_VALIDATE_FORM: 'MINING_CREATE_VALIDATE_FORM',

  MINING_CREATE_LOAD_POOL: 'MINING_CREATE_LOAD_POOL',
  MINING_CREATE_LOAD_POOL_ERROR: 'MINING_CREATE_LOAD_POOL_ERROR',
  MINING_CREATE_LOAD_POOL_SUCCESS: 'MINING_CREATE_LOAD_POOL_SUCCESS'
}