export default {
  CONVERT_UPDATE_FORM: 'CONVERT_UPDATE_FORM',
  INIT_CONVERT: 'INIT_CONVERT',
  CONVERT_UPDATE_RATES: 'CONVERT_UPDATE_RATES',
  CONVERT_FETCH_FORM: 'CONVERT_FETCH_FORM',
  CONVERT_FETCH_FORM_ERROR: 'CONVERT_FETCH_FORM_ERROR',
  CONVERT_FETCH_FORM_SUCCESS: 'CONVERT_FETCH_FORM_SUCCESS',
  CONVERT_UPDATE_INPUTS: 'CONVERT_UPDATE_INPUTS',
  CONVERT_UPDATE_INPUTS_2A: 'CONVERT_UPDATE_INPUTS_2A'
}
