export default {
  SETTINGS_API_FETCH_CURRENT: 'SETTINGS_API_FETCH_CURRENT',
  SETTINGS_API_FETCH_CURRENT_ERROR: 'SETTINGS_API_FETCH_CURRENT_ERROR',
  SETTINGS_API_FETCH_CURRENT_SUCCESS: 'SETTINGS_API_FETCH_CURRENT_SUCCESS',

  SETTINGS_API_FETCH_UPDATE_CURRENT: 'SETTINGS_API_FETCH_UPDATE_CURRENT',
  SETTINGS_API_FETCH_UPDATE_CURRENT_ERROR: 'SETTINGS_API_FETCH_UPDATE_CURRENT_ERROR',
  SETTINGS_API_FETCH_UPDATE_CURRENT_SUCCESS: 'SETTINGS_API_FETCH_UPDATE_CURRENT_SUCCESS',

  SETTINGS_API_FETCH_UPDATE_CURRENT_RULE: 'SETTINGS_API_FETCH_UPDATE_CURRENT_RULE',
  SETTINGS_API_FETCH_UPDATE_CURRENT_RULE_ERROR: 'SETTINGS_API_FETCH_UPDATE_CURRENT_RULE_ERROR',
  SETTINGS_API_FETCH_UPDATE_CURRENT_RULE_SUCCESS: 'SETTINGS_API_FETCH_UPDATE_CURRENT_RULE_SUCCESS',

  SETTINGS_API_UPDATE_CURRENT: 'SETTINGS_API_UPDATE_CURRENT',
  SETTINGS_API_UPDATE_CURRENT_RULE: 'SETTINGS_API_UPDATE_CURRENT_RULE',

  SETTINGS_API_ADD_IP: 'SETTINGS_API_ADD_IP',
  SETTINGS_API_ADD_IP_ERROR: 'SETTINGS_API_ADD_IP_ERROR',
  SETTINGS_API_ADD_IP_SUCCESS: 'SETTINGS_API_ADD_IP_SUCCESS',

  SETTINGS_API_DELETE_IP: 'SETTINGS_API_DELETE_IP',
  SETTINGS_API_DELETE_IP_ERROR: 'SETTINGS_API_DELETE_IP_ERROR',
  SETTINGS_API_DELETE_IP_SUCCESS: 'SETTINGS_API_DELETE_IP_SUCCESS'
};
