export default {
  WITHDRAW_FIAT_UPDATE_FORM: 'WITHDRAW_FIAT_UPDATE_FORM',

  WITHDRAW_FIAT_FETCH_WITHDRAW: 'WITHDRAW_FIAT_FETCH_WITHDRAW',
  WITHDRAW_FIAT_FETCH_WITHDRAW_ERROR: 'WITHDRAW_FIAT_FETCH_WITHDRAW_ERROR',
  WITHDRAW_FIAT_FETCH_WITHDRAW_SUCCESS: 'WITHDRAW_FIAT_FETCH_WITHDRAW_SUCCESS'
}