export default {
  COUPON_APPLY_UPDATE_FORM: 'COUPON_ACTIVATE_UPDATE_FORM',
  COUPON_APPLY_VALIDATE_FORM: 'COUPON_APPLY_VALIDATE_FORM',
  
  COUPON_APPLY_SEND_FORM: 'COUPON_APPLY_SEND_FORM',
  COUPON_APPLY_SEND_FORM_ERROR: 'COUPON_APPLY_SEND_FORM_ERROR',
  COUPON_APPLY_SEND_FORM_SUCCESS: 'COUPON_APPLY_SEND_FORM_SUCCESS'
};