export default Object.assign({
  TRANSACTIONS_FETCH_LIST: 'TRANSACTIONS_FETCH_LIST',
  TRANSACTIONS_FETCH_LIST_ERROR: 'TRANSACTIONS_FETCH_LIST_ERROR',
  TRANSACTIONS_FETCH_LIST_SUCCESS: 'TRANSACTIONS_FETCH_LIST_SUCCESS',
  TRANSACTIONS_UPDATE_LIST: 'TRANSACTIONS_UPDATE_LIST',
  TRANSACTIONS_LEAVE_PAGE: 'TRANSACTIONS_LEAVE_PAGE',
  TRANSACTIONS_UPDATE_FILTER: 'TRANSACTIONS_UPDATE_FILTER'
});