export default {
  SETTINGS_API_FETCH_CREATE: 'SETTINGS_API_FETCH_CREATE',
  SETTINGS_API_FETCH_CREATE_ERROR: 'SETTINGS_API_FETCH_CREATE_ERROR',
  SETTINGS_API_FETCH_CREATE_SUCCESS: 'SETTINGS_API_FETCH_CREATE_SUCCESS',

  SETTINGS_API_FETCH_LIST_KEYS: 'SETTINGS_API_FETCH_LIST_KEYS',
  SETTINGS_API_FETCH_LIST_KEYS_ERROR: 'SETTINGS_API_FETCH_LIST_KEYS_ERROR',
  SETTINGS_API_FETCH_LIST_KEYS_SUCCESS: 'SETTINGS_API_FETCH_LIST_KEYS_SUCCESS',

  SETTINGS_API_UPDATE_CREATE_FORM: 'SETTINGS_API_UPDATE_CREATE_FORM'
};
